# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

require File.expand_path('../config/application', __FILE__)
require './app/models/riot'
Rails.application.load_tasks

require 'CSV'
namespace :data do
  desc "Import race riots"
	CSV.foreach('Riots.csv', :headers => true) do |row|
      riot = Riot.create (row.to_hash)
      puts row.to_hash
      #Riot.save!
  end
end
